
const CSV_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vRaaomIQn_nLvIPERtpget8Y20iSDY_3pSlEGfwhzkvMfUHXIQ2P3XvQ0R0IB6SX4hBEonVRcvxXsIl/pub?output=csv";
let quotes=[],homeIndices=[],homePos=0,sectionIndices=[],sectionPos=0,activeSection="",touchStartX=0,touchStartY=0;
let favorites=new Set(JSON.parse(localStorage.getItem('dhammaDailyFavorites')||'[]'));
function favKey(q){return dateKey(q.date)+'|'+q.quote;}
function isFavorite(q){return favorites.has(favKey(q));}
function toggleFavorite(index, mode='home'){const q=quotes[index];if(!q)return;const k=favKey(q);if(favorites.has(k))favorites.delete(k);else favorites.add(k);localStorage.setItem('dhammaDailyFavorites',JSON.stringify([...favorites]));if(mode==='section')renderSectionQuote();else if(mode==='sectionBrowse')renderSectionList();else renderHomeQuote();renderFavorites();}
function parseCSV(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++;continue}if(c==='"'){quoted=!quoted;continue}if(c===','&&!quoted){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(x=>x.trim()!==''))rows.push(row);row=[];continue}cell+=c}if(cell!==''||row.length){row.push(cell);if(row.some(x=>x.trim()!==''))rows.push(row)}if(!rows.length)return[];const headers=rows.shift().map(h=>h.trim().toLowerCase());return rows.map(r=>{const o={};headers.forEach((h,i)=>o[h]=(r[i]||'').trim());return o}).filter(x=>x.date&&x.quote)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function dateParts(s){const raw=String(s||'').trim();let m;if((m=raw.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/)))return{year:+m[1],month:+m[2],day:+m[3],key:String(+m[2]).padStart(2,'0')+'-'+String(+m[3]).padStart(2,'0')};if((m=raw.match(/^(\d{1,2})[\/-](\d{1,2})(?:[\/-](\d{4}))?$/)))return{year:m[3]?+m[3]:null,month:+m[2],day:+m[1],key:String(+m[2]).padStart(2,'0')+'-'+String(+m[1]).padStart(2,'0')};const d=new Date(raw);if(!isNaN(d))return{year:d.getFullYear(),month:d.getMonth()+1,day:d.getDate(),key:String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};return{year:null,month:null,day:null,key:raw}}
function dateKey(s){return dateParts(s).key}function niceDate(s){const p=dateParts(s);if(!p.month||!p.day)return s;return new Date(2000,p.month-1,p.day).toLocaleDateString(undefined,{day:'numeric',month:'long'})}function todayKey(){const d=new Date();return String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function showPage(page){['home','days','sections','favorites','pledge','practice','month'].forEach(p=>document.getElementById(p).classList.toggle('hidden',p!==page));['home','days','sections','pledge','practice'].forEach(p=>document.getElementById('nav-'+p).classList.toggle('active',p===page));if(page!=='sections'){resetSectionViews()}if(page==='month')renderMonth();if(page==='practice')loadPracticeForm();window.scrollTo({top:0,behavior:'smooth'})}
function resetSectionViews(){document.getElementById('sectionBrowse').classList.remove('hidden');document.getElementById('sectionQuoteBrowse').classList.add('hidden');document.getElementById('sectionViewerWrap').classList.add('hidden')}
function renderSectionList(){const list=document.getElementById('sectionQuoteList');const title=document.getElementById('sectionQuoteTitle');title.textContent=activeSection;list.innerHTML=sectionIndices.map((i,pos)=>{const q=quotes[i],fav=isFavorite(q);return `<div class="item section-quote-item" onclick="openSectionQuote(${pos})"><div class="item-date">${esc(niceDate(q.date))}</div><div class="item-text">${esc(q.quote)}</div>${q.author?`<div class="item-section">— ${esc(q.author)}</div>`:''}<button class="fav-btn section-quote-fav ${fav?'active':''}" aria-label="${fav?'Remove from favorites':'Add to favorites'}" onclick="event.stopPropagation();toggleFavorite(${i},'sectionBrowse')">${fav?'★':'☆'}</button></div>`}).join('')}
function openSectionQuote(pos){sectionPos=Math.max(0,Math.min(pos,sectionIndices.length-1));document.getElementById('sectionQuoteBrowse').classList.add('hidden');document.getElementById('sectionViewerWrap').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});renderSectionQuote()}
function renderHomeQuote(label=''){if(!homeIndices.length)return;const q=quotes[homeIndices[homePos]],pos=homePos,total=homeIndices.length;document.getElementById('todayCard').innerHTML=`<div class="viewer"><div class="quote-top"><div class="date">${label?esc(label)+' · ':''}${esc(niceDate(q.date))}</div><button class="fav-btn ${isFavorite(q)?'active':''}" aria-label="${isFavorite(q)?'Remove from favorites':'Add to favorites'}" onclick="toggleFavorite(${homeIndices[homePos]})">${isFavorite(q)?'★':'☆'}</button></div><div class="quote">${esc(q.quote)}</div>${q.author?`<div class="author">— ${esc(q.author)}</div>`:''}<div class="small" style="margin-top:15px">${esc(q.section||'')}</div><div class="actions"><button class="btn" ${pos<=0?'disabled':''} onclick="moveHome(-1)">← Previous</button><span class="small">${pos+1} / ${total}</span><button class="btn primary" ${pos>=total-1?'disabled':''} onclick="moveHome(1)">Next →</button></div></div>`}
function moveHome(delta){const n=homePos+delta;if(n<0||n>=homeIndices.length)return;homePos=n;renderHomeQuote();window.scrollTo({top:0,behavior:'smooth'})}
function openDay(i){homeIndices=quotes.map((_,x)=>x);homePos=Math.max(0,i);showPage('home');renderHomeQuote();}
function renderSectionQuote(){if(!sectionIndices.length)return;const q=quotes[sectionIndices[sectionPos]],pos=sectionPos,total=sectionIndices.length;document.getElementById('sectionViewer').innerHTML=`<div class="viewer"><div class="quote-top"><div class="date">${esc(niceDate(q.date))}</div><button class="fav-btn ${isFavorite(q)?'active':''}" aria-label="${isFavorite(q)?'Remove from favorites':'Add to favorites'}" onclick="toggleFavorite(${sectionIndices[sectionPos]},'section')">${isFavorite(q)?'★':'☆'}</button></div><div class="quote">${esc(q.quote)}</div>${q.author?`<div class="author">— ${esc(q.author)}</div>`:''}<div class="small" style="margin-top:15px">${esc(q.section||activeSection)}</div><div class="actions"><button class="btn" ${pos<=0?'disabled':''} onclick="moveSection(-1)">← Previous</button><span class="small">${pos+1} / ${total}</span><button class="btn primary" ${pos>=total-1?'disabled':''} onclick="moveSection(1)">Next →</button></div></div>`}
function moveSection(delta){const n=sectionPos+delta;if(n<0||n>=sectionIndices.length)return;sectionPos=n;renderSectionQuote();window.scrollTo({top:0,behavior:'smooth'})}
function showSection(s){activeSection=s;sectionIndices=quotes.map((q,i)=>({q,i})).filter(o=>(o.q.section||'Other')===s).map(o=>o.i);sectionPos=0;document.getElementById('sectionBrowse').classList.add('hidden');document.getElementById('sectionQuoteBrowse').classList.remove('hidden');document.getElementById('sectionViewerWrap').classList.add('hidden');renderSectionList();window.scrollTo({top:0,behavior:'smooth'});}
function backToSections(){resetSectionViews();window.scrollTo({top:0,behavior:'smooth'})}
function openFavorite(i){homeIndices=quotes.map((q,x)=>isFavorite(q)?x:null).filter(x=>x!==null);homePos=homeIndices.indexOf(i);if(homePos<0)homePos=0;showPage('home');renderHomeQuote('Favorites');}
function renderFavorites(){const list=document.getElementById('favoritesList');const ids=quotes.map((q,i)=>isFavorite(q)?i:null).filter(i=>i!==null);if(!ids.length){list.innerHTML='<div class="status">No favorites yet.<br><br>Tap ☆ on any thought to bookmark it here.</div>';return;}list.innerHTML=ids.map(i=>{const q=quotes[i];return `<div class="item" onclick="openFavorite(${i})"><div class="item-date">${esc(niceDate(q.date))}</div><div class="item-text">${esc(q.quote)}</div><div class="item-section">${esc(q.section||'')}</div></div>`}).join('');}
function renderLists(){document.getElementById('daysList').innerHTML=quotes.map((q,i)=>`<div class="item" onclick="openDay(${i})"><div class="item-date">${esc(niceDate(q.date))}</div><div class="item-text">${esc(q.quote)}</div><div class="item-section">${esc(q.section||'')}</div></div>`).join('');const counts={};quotes.forEach(q=>{const s=q.section||'Other';counts[s]=(counts[s]||0)+1});const list=document.getElementById('sectionList');list.innerHTML='';Object.entries(counts).sort((a,b)=>a[0].localeCompare(b[0])).forEach(([s,n])=>{const b=document.createElement('button');b.className='chip';b.type='button';b.innerHTML=`<b>${esc(s)}</b><span>${n} ${n===1?'thought':'thoughts'}</span>`;b.addEventListener('click',()=>showSection(s));list.appendChild(b)})}

const PRACTICE_KEY='dhammaDailyPracticeV1';
let practiceRecords=JSON.parse(localStorage.getItem(PRACTICE_KEY)||'{}');
function localISO(d=new Date()){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function shiftISO(iso,days){const d=new Date(iso+'T12:00:00');d.setDate(d.getDate()+days);return localISO(d)}
function displayISO(iso){if(!iso)return '';const d=new Date(iso+'T12:00:00');return d.toLocaleDateString('te-IN',{day:'numeric',month:'short',year:'numeric'})}
function selectedDate(){return document.getElementById('practiceDate').value||localISO()}
function getRecord(iso){return practiceRecords[iso]||{pledge:false,sit:false,reviewDone:false,minutes:'',comment:'',skipComment:false}}
function saveAll(){localStorage.setItem(PRACTICE_KEY,JSON.stringify(practiceRecords))}
function levelForMinutes(n){if(n===null||n===undefined||n===''||!Number.isFinite(Number(n))||Number(n)<15)return null;n=Number(n);if(n>=120)return{symbol:'🪷',name:'బోధి దినం',threshold:120};if(n>=60)return{symbol:'⭐',name:'అత్యుత్తమం',threshold:60};if(n>=30)return{symbol:'💎',name:'ఉత్తమం',threshold:30};return{symbol:'👍',name:'ప్రగతి',threshold:15}}
function levelForDay(r){const minuteLevel=levelForMinutes(r.minutes);if(minuteLevel)return minuteLevel;if(r.pledge&&r.sit&&r.reviewDone)return{symbol:'🏆',name:'విజయం'};if(r.restDay)return{symbol:'⏸️',name:'విరామం'};return null}
function loadPracticeForm(){const date=document.getElementById('practiceDate');if(!date.value)date.value=localISO();const r=getRecord(date.value);document.getElementById('taskPledge').checked=!!r.pledge;document.getElementById('taskSit').checked=!!r.sit;document.getElementById('taskReview').checked=!!r.reviewDone;document.getElementById('practiceMinutes').value=r.minutes??'';document.getElementById('victoryLevel').classList.toggle('hidden',!(r.pledge&&r.sit&&r.reviewDone));const reviewDay=shiftISO(date.value,-1),rr=getRecord(reviewDay);document.getElementById('reviewText').value=rr.comment||'';document.getElementById('skipReview').checked=!!rr.skipComment;document.getElementById('reviewText').disabled=!!rr.skipComment;renderMinuteLevel()}
function savePractice(){const iso=selectedDate(),r=getRecord(iso);r.pledge=document.getElementById('taskPledge').checked;r.sit=document.getElementById('taskSit').checked;r.reviewDone=document.getElementById('taskReview').checked;r.minutes=document.getElementById('practiceMinutes').value;practiceRecords[iso]=r;saveAll();document.getElementById('victoryLevel').classList.toggle('hidden',!(r.pledge&&r.sit&&r.reviewDone));renderMinuteLevel()}
function saveReview(){const target=shiftISO(selectedDate(),-1),r=getRecord(target);r.comment=document.getElementById('reviewText').value;r.skipComment=false;practiceRecords[target]=r;document.getElementById('skipReview').checked=false;saveAll()}
let speechRecognition=null,voiceListening=false,voiceStopRequested=false,voiceBaseText='',voiceSessionResults=[];
function voiceMessage(msg,listening=false){const el=document.getElementById('voiceStatus');el.textContent=msg;el.classList.toggle('listening',listening)}
function startVoiceRecognition(SpeechRecognition){
  if(voiceStopRequested)return;
  try{
    speechRecognition=new SpeechRecognition();
    speechRecognition.lang='te-IN';
    speechRecognition.continuous=false;
    speechRecognition.interimResults=false;
    voiceSessionResults=[];
    speechRecognition.onstart=()=>{voiceListening=true;document.getElementById('voiceButton').textContent='🎙️ వింటోంది…';document.getElementById('voiceStopButton').classList.remove('hidden');voiceMessage('వింటోంది… వాక్యం పూర్తయ్యాక ఆపండి.',true)};
    speechRecognition.onresult=(event)=>{
      const received=[];
      for(let i=0;i<event.results.length;i++){
        const result=event.results[i];
        if(!result.isFinal)continue;
        const text=(result[0].transcript||'').trim();
        if(text && received[received.length-1]!==text)received.push(text);
      }
      // This is a one-shot recognition session: replace the current session text,
      // rather than appending the same cumulative result every time an event fires.
      voiceSessionResults=received;
      const recognized=received.join(' ').trim();
      document.getElementById('reviewText').value=[voiceBaseText,recognized].filter(Boolean).join(' ');
      saveReview();
    };
    speechRecognition.onerror=(event)=>{
      const msgs={'not-allowed':'మైక్రోఫోన్ అనుమతి ఇవ్వండి. బ్రౌజర్ సెట్టింగ్స్‌లో అనుమతిని పరిశీలించండి.','service-not-allowed':'ఈ బ్రౌజర్‌లో వాయిస్ గుర్తింపు సేవ అందుబాటులో లేదు. కీబోర్డ్ మైక్‌ను ఉపయోగించండి.','network':'వాయిస్ గుర్తింపుకు ఇంటర్నెట్ అవసరం కావచ్చు. కనెక్షన్‌ను పరిశీలించండి.','no-speech':'మాటలు గుర్తించబడలేదు. మళ్లీ ప్రయత్నించండి.'};
      voiceMessage(msgs[event.error]||('వాయిస్ గుర్తింపు సమస్య: '+event.error),false);
      if(event.error==='not-allowed'||event.error==='service-not-allowed')voiceStopRequested=true;
    };
    speechRecognition.onend=()=>{
      voiceListening=false;
      const recognized=voiceSessionResults.join(' ').trim();
      document.getElementById('reviewText').value=[voiceBaseText,recognized].filter(Boolean).join(' ');
      saveReview();
      document.getElementById('voiceButton').textContent='🎙️ మళ్లీ మాట్లాడండి';
      document.getElementById('voiceStopButton').classList.add('hidden');
      if(voiceStopRequested)voiceMessage('పూర్తయింది. అవసరమైతే సవరించి సేవ్ చేయండి.');
      else voiceMessage(recognized?'రికార్డింగ్ పూర్తయింది. అవసరమైతే మళ్లీ మాట్లాడండి లేదా సవరించండి.':'మాటలు నమోదు కాలేదు. మళ్లీ ప్రయత్నించండి; సమస్య కొనసాగితే కీబోర్డ్ మైక్‌ను ఉపయోగించండి.');
    };
    speechRecognition.start();
  }catch(e){voiceListening=false;voiceStopRequested=true;document.getElementById('voiceStopButton').classList.add('hidden');voiceMessage('మైక్ ప్రారంభం కాలేదు. బ్రౌజర్ అనుమతులు పరిశీలించి మళ్లీ ప్రయత్నించండి.');}
}
function toggleVoiceInput(){if(voiceListening){stopVoiceInput();return}const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition){voiceMessage('ఈ బ్రౌజర్‌లో నేరుగా వాయిస్ గుర్తింపు అందుబాటులో లేదు. కీబోర్డ్ మైక్‌ను ఉపయోగించండి.');return}if(document.getElementById('skipReview').checked){voiceMessage('ముందుగా వ్యాఖ్య రాయదలచుకోలేదు అనే ఎంపికను తీసివేయండి.');return}voiceStopRequested=false;voiceBaseText=document.getElementById('reviewText').value.trim();startVoiceRecognition(SpeechRecognition)}
function stopVoiceInput(){voiceStopRequested=true;if(speechRecognition&&voiceListening){try{speechRecognition.stop()}catch(e){voiceListening=false;document.getElementById('voiceButton').textContent='🎙️ మళ్లీ మాట్లాడండి';document.getElementById('voiceStopButton').classList.add('hidden');voiceMessage('పూర్తయింది. అవసరమైతే సవరించి సేవ్ చేయండి.');saveReview()}}else{voiceListening=false;document.getElementById('voiceButton').textContent='🎙️ మళ్లీ మాట్లాడండి';document.getElementById('voiceStopButton').classList.add('hidden');voiceMessage('పూర్తయింది. అవసరమైతే సవరించి సేవ్ చేయండి.');saveReview()}}

function toggleSkipReview(){const target=shiftISO(selectedDate(),-1),r=getRecord(target);r.skipComment=document.getElementById('skipReview').checked;if(r.skipComment){r.comment='';document.getElementById('reviewText').value='';document.getElementById('reviewText').disabled=true}else document.getElementById('reviewText').disabled=false;practiceRecords[target]=r;saveAll()}
function renderMinuteLevel(){const el=document.getElementById('minutesLevel'),level=levelForMinutes(document.getElementById('practiceMinutes').value);if(!level){el.classList.add('hidden');el.innerHTML='';return}el.classList.remove('hidden');el.innerHTML=`<span class="symbol">${level.symbol}</span>${level.name}`}
function setMonthView(v){const summary=v==='summary';document.getElementById('monthSummary').classList.toggle('hidden',!summary);document.getElementById('monthDaily').classList.toggle('hidden',summary);document.getElementById('summaryToggle').classList.toggle('primary',summary);document.getElementById('dailyToggle').classList.toggle('primary',!summary)}
function renderMonth(){const mp=document.getElementById('monthPicker');if(!mp.value)mp.value=localISO().slice(0,7);const month=mp.value;const days=Object.keys(practiceRecords).filter(d=>d.startsWith(month)).sort();let practiceDays=0,vijayamDays=0,minuteSum=0;const counts={'ప్రగతి':0,'ఉత్తమం':0,'అత్యుత్తమం':0,'బోధి దినం':0,'విరామం':0};days.forEach(d=>{const r=practiceRecords[d];const mins=Number(r.minutes);if(r.minutes!==''&&r.minutes!=null&&Number.isFinite(mins)&&mins>0){practiceDays++;minuteSum+=mins;const lvl=levelForMinutes(mins);if(lvl)counts[lvl.name]++;}if(r.pledge&&r.sit&&r.reviewDone)vijayamDays++;if(r.restDay)counts['విరామం']++});const avg=practiceDays?(minuteSum/practiceDays).toFixed(1):'—';document.getElementById('monthSummary').innerHTML=`<div class="grid"><div class="practice-card headline-card"><div class="headline-icon" aria-hidden="true">🪷</div><div class="headline-copy"><div class="small">సాధన చేసిన రోజులు</div><h2>${practiceDays}</h2></div></div><div class="practice-card headline-card"><div class="headline-icon" aria-hidden="true">🏆</div><div class="headline-copy"><div class="small">విజయము సాధించిన రోజులు</div><h2>${vijayamDays}</h2></div></div></div><div class="practice-card" style="text-align:center"><div class="small">ఈ నెల సగటు సాధన సమయం</div><h2>${avg}${avg==='—'?'':' నిమిషాలు'}</h2><div class="small">సాధన చేసిన రోజులకు సగటు</div></div><div class="practice-card level-summary"><h3>స్థాయిల వారీగా సాధన చేసిన రోజులు</h3>${[['👍','ప్రగతి'],['💎','ఉత్తమం'],['⭐','అత్యుత్తమం'],['🪷','బోధి దినం'],['⏸️','విరామం']].map(([e,n])=>`<div class="level-row"><span>${e} ${n}</span><b>${counts[n]}</b></div>`).join('')}</div>`;const allDates=[];const [yy,mm]=month.split('-').map(Number);const total=new Date(yy,mm,0).getDate();const today=localISO();const monthIsFuture=month>today.slice(0,7);const lastDay=monthIsFuture?0:(month===today.slice(0,7)?Math.min(total,Number(today.slice(8,10))):total);for(let i=1;i<=lastDay;i++)allDates.push(`${month}-${String(i).padStart(2,'0')}`);document.getElementById('monthDaily').innerHTML=`<div class="table-wrap"><table class="daily-table"><thead><tr><th>తేదీ</th><th>విజయము</th><th>సాధన స్థాయి</th><th>సమీక్ష</th></tr></thead><tbody>${allDates.length?allDates.map(d=>{const r=getRecord(d),v=r.pledge&&r.sit&&r.reviewDone?'🏆 విజయము':'—',l=levelForMinutes(r.minutes),level=l?l.symbol+' '+l.name:(r.restDay?'⏸️ విరామం':'—');const comment=r.skipComment?'సమీక్షను వదిలివేశారు':(r.comment||'—');return `<tr><td>${esc(displayISO(d))}</td><td>${esc(v)}</td><td>${esc(level)}</td><td>${esc(comment)}</td></tr>`}).join(''):'<tr><td colspan="4" style="text-align:center">ఈ నెలకు ఇంకా తేదీలు లేవు</td></tr>'}</tbody></table></div>`;setMonthView(window.monthView||'summary')}

function renderWelcomeDate(){const now=new Date();const text=new Intl.DateTimeFormat('te-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(now);document.getElementById('welcomeDate').textContent=text;}

function setupSwipe(){const targets=[document.getElementById('todayCard'),document.getElementById('sectionViewer')];targets.forEach(card=>{card.addEventListener('touchstart',e=>{if(e.touches.length===1){touchStartX=e.touches[0].clientX;touchStartY=e.touches[0].clientY}},{passive:true});card.addEventListener('touchend',e=>{if(touchStartX===0)return;const dx=e.changedTouches[0].clientX-touchStartX,dy=e.changedTouches[0].clientY-touchStartY;touchStartX=touchStartY=0;if(Math.abs(dx)<60||Math.abs(dx)<=Math.abs(dy))return;if(card.id==='sectionViewer')moveSection(dx<0?1:-1);else moveHome(dx<0?1:-1)},{passive:true})})}
async function load(){try{const res=await fetch(CSV_URL+'&_='+Date.now(),{cache:'no-store'});if(!res.ok)throw Error();quotes=parseCSV(await res.text());quotes.sort((a,b)=>dateKey(a.date).localeCompare(dateKey(b.date)));if(!quotes.length)throw Error();document.getElementById('subtitle').textContent=`${quotes.length} thoughts · updated from your collection`;renderLists();renderFavorites();renderPledge();setupSwipe();homeIndices=quotes.map((_,i)=>i);const idx=quotes.findIndex(q=>dateKey(q.date)===todayKey());homePos=idx>=0?idx:quotes.length-1;renderHomeQuote(idx>=0?"Today's thought":"Latest available");localStorage.setItem('dhammaDailyQuotes',JSON.stringify(quotes))}catch(e){const c=localStorage.getItem('dhammaDailyQuotes')||localStorage.getItem('forAmmaQuotes');if(c){quotes=JSON.parse(c);renderLists();renderFavorites();renderPledge();setupSwipe();homeIndices=quotes.map((_,i)=>i);const idx=quotes.findIndex(q=>dateKey(q.date)===todayKey());homePos=idx>=0?idx:quotes.length-1;renderHomeQuote(idx>=0?"Today's thought":"Latest available")}else document.getElementById('todayCard').innerHTML='<div class="status"><b>Couldn\'t load the collection.</b><br><br>Please check the internet connection and open the app again.</div>'}}
renderWelcomeDate();document.getElementById('practiceDate').max=localISO();document.getElementById('practiceDate').value=localISO();document.getElementById('practiceDate').addEventListener('change',()=>{const el=document.getElementById('practiceDate');if(el.value>localISO())el.value=localISO();loadPracticeForm()});document.getElementById('monthPicker').max=localISO().slice(0,7);document.getElementById('monthPicker').addEventListener('change',()=>{const el=document.getElementById('monthPicker');if(el.value>localISO().slice(0,7))el.value=localISO().slice(0,7);renderMonth()});
function renderPledge(){const qs=quotes.filter(q=>(q.section||'').trim().toLowerCase()==='daily pledge');document.getElementById('pledgeList').innerHTML=qs.length?qs.map(q=>`<div class="pledge-item">${esc(q.quote)}</div>`).join(''):'<div class="status">Daily Pledge section quotes were not found. Please name that section “Daily Pledge” in your Google Sheet.</div>'}
load();
